import { defineConfig } from 'oxfmt';

export default defineConfig({
  printWidth: 100,
  endOfLine: 'lf',
  bracketSpacing: true,
  singleQuote: true,
  trailingComma: 'all',
  semi: true,
  arrowParens: 'always',
  bracketSameLine: true,
  insertPragma: false,
  jsxBracketSameLine: false,
  jsxSingleQuote: true,
  proseWrap: 'always',
  quoteProps: 'as-needed',
  requirePragma: false,
  tabWidth: 2,
  sortImports: {
    groups: [
      'type-import',
      ['value-builtin', 'value-external'],
      'type-internal',
      'value-internal',
      ['type-parent', 'type-sibling', 'type-index'],
      ['value-parent', 'value-sibling', 'value-index'],
      'unknown',
    ],
  },
  sortTailwindcss: {
    stylesheet: './src/styles/global.css',
    functions: ['clsx', 'cn'],
    preserveWhitespace: true,
  },
  ignorePatterns: [
    '**/node_modules/**',
    '**/dist/**',
    '**/build/**',
    '**/.git/**',
    '**/.tanstack/**',
    '**/.turbo/**',
    '**/.next/**',
    '**/.output/**',
    '**/dist/**',
    '**/coverage/**',
    '**/public/**',
    '**/vendor/**',
    '**/test/snapshots/**',
    '**/graveyard/**',
    '**/widgets/**',
  ],
});
