export type TimezoneString = (typeof timezones)[keyof typeof timezones][number]['zone'];

export const timezones = {
  America: [
    { city: 'Buenos Aires', zone: 'America/Argentina/Buenos_Aires' },
    { city: 'Cordoba', zone: 'America/Argentina/Cordoba' },
    { city: 'Salta', zone: 'America/Argentina/Salta' },
    { city: 'Jujuy', zone: 'America/Argentina/Jujuy' },
    { city: 'Tucuman', zone: 'America/Argentina/Tucuman' },
    { city: 'Catamarca', zone: 'America/Argentina/Catamarca' },
    { city: 'La Rioja', zone: 'America/Argentina/La_Rioja' },
    { city: 'San Juan', zone: 'America/Argentina/San_Juan' },
    { city: 'Mendoza', zone: 'America/Argentina/Mendoza' },
    { city: 'San Luis', zone: 'America/Argentina/San_Luis' },
    { city: 'Rio Gallegos', zone: 'America/Argentina/Rio_Gallegos' },
    { city: 'Ushuaia', zone: 'America/Argentina/Ushuaia' },
    { city: 'Barbados', zone: 'America/Barbados' },
    { city: 'La Paz', zone: 'America/La_Paz' },
    { city: 'Belem', zone: 'America/Belem' },
    { city: 'Fortaleza', zone: 'America/Fortaleza' },
    { city: 'Recife', zone: 'America/Recife' },
    { city: 'Araguaina', zone: 'America/Araguaina' },
    { city: 'Maceio', zone: 'America/Maceio' },
    { city: 'Bahia', zone: 'America/Bahia' },
    { city: 'Sao Paulo', zone: 'America/Sao_Paulo' },
    { city: 'Campo Grande', zone: 'America/Campo_Grande' },
    { city: 'Cuiaba', zone: 'America/Cuiaba' },
    { city: 'Porto Velho', zone: 'America/Porto_Velho' },
    { city: 'Boa Vista', zone: 'America/Boa_Vista' },
    { city: 'Manaus', zone: 'America/Manaus' },
    { city: 'Eirunepe', zone: 'America/Eirunepe' },
    { city: 'Rio Branco', zone: 'America/Rio_Branco' },
    { city: 'Nassau', zone: 'America/Nassau' },
    { city: 'Belize', zone: 'America/Belize' },
    { city: 'St Johns', zone: 'America/St_Johns' },
    { city: 'Halifax', zone: 'America/Halifax' },
    { city: 'Glace Bay', zone: 'America/Glace_Bay' },
    { city: 'Moncton', zone: 'America/Moncton' },
    { city: 'Goose Bay', zone: 'America/Goose_Bay' },
    { city: 'Blanc-Sablon', zone: 'America/Blanc-Sablon' },
    { city: 'Toronto', zone: 'America/Toronto' },
    { city: 'Nipigon', zone: 'America/Nipigon' },
    { city: 'Thunder Bay', zone: 'America/Thunder_Bay' },
    { city: 'Iqaluit', zone: 'America/Iqaluit' },
    { city: 'Pangnirtung', zone: 'America/Pangnirtung' },
    { city: 'Atikokan', zone: 'America/Atikokan' },
    { city: 'Winnipeg', zone: 'America/Winnipeg' },
    { city: 'Rainy River', zone: 'America/Rainy_River' },
    { city: 'Resolute', zone: 'America/Resolute' },
    { city: 'Rankin Inlet', zone: 'America/Rankin_Inlet' },
    { city: 'Regina', zone: 'America/Regina' },
    { city: 'Swift Current', zone: 'America/Swift_Current' },
    { city: 'Edmonton', zone: 'America/Edmonton' },
    { city: 'Cambridge Bay', zone: 'America/Cambridge_Bay' },
    { city: 'Yellowknife', zone: 'America/Yellowknife' },
    { city: 'Inuvik', zone: 'America/Inuvik' },
    { city: 'Creston', zone: 'America/Creston' },
    { city: 'Dawson Creek', zone: 'America/Dawson_Creek' },
    { city: 'Fort Nelson', zone: 'America/Fort_Nelson' },
    { city: 'Vancouver', zone: 'America/Vancouver' },
    { city: 'Whitehorse', zone: 'America/Whitehorse' },
    { city: 'Dawson', zone: 'America/Dawson' },
    { city: 'Santiago', zone: 'America/Santiago' },
    { city: 'Punta Arenas', zone: 'America/Punta_Arenas' },
    { city: 'Bogota', zone: 'America/Bogota' },
    { city: 'Costa Rica', zone: 'America/Costa_Rica' },
    { city: 'Havana', zone: 'America/Havana' },
    { city: 'Curacao', zone: 'America/Curacao' },
    { city: 'Santo Domingo', zone: 'America/Santo_Domingo' },
    { city: 'Guayaquil', zone: 'America/Guayaquil' },
    { city: 'Cayenne', zone: 'America/Cayenne' },
    { city: 'Godthab', zone: 'America/Godthab' },
    { city: 'Danmarkshavn', zone: 'America/Danmarkshavn' },
    { city: 'Scoresbysund', zone: 'America/Scoresbysund' },
    { city: 'Thule', zone: 'America/Thule' },
    { city: 'Guatemala', zone: 'America/Guatemala' },
    { city: 'Guyana', zone: 'America/Guyana' },
    { city: 'Tegucigalpa', zone: 'America/Tegucigalpa' },
    { city: 'Port-au-Prince', zone: 'America/Port-au-Prince' },
    { city: 'Jamaica', zone: 'America/Jamaica' },
    { city: 'Martinique', zone: 'America/Martinique' },
    { city: 'Mexico City', zone: 'America/Mexico_City' },
    { city: 'Cancun', zone: 'America/Cancun' },
    { city: 'Merida', zone: 'America/Merida' },
    { city: 'Monterrey', zone: 'America/Monterrey' },
    { city: 'Matamoros', zone: 'America/Matamoros' },
    { city: 'Caracas', zone: 'America/Caracas' },
    { city: 'Mazatlan', zone: 'America/Mazatlan' },
    { city: 'Chihuahua', zone: 'America/Chihuahua' },
    { city: 'Ojinaga', zone: 'America/Ojinaga' },
    { city: 'Hermosillo', zone: 'America/Hermosillo' },
    { city: 'Tijuana', zone: 'America/Tijuana' },
    { city: 'Bahia Banderas', zone: 'America/Bahia_Banderas' },
    { city: 'Managua', zone: 'America/Managua' },
    { city: 'Panama', zone: 'America/Panama' },
    { city: 'Lima', zone: 'America/Lima' },
    { city: 'Miquelon', zone: 'America/Miquelon' },
    { city: 'Puerto Rico', zone: 'America/Puerto_Rico' },
    { city: 'El Salvador', zone: 'America/El_Salvador' },
    { city: 'Grand Turk', zone: 'America/Grand_Turk' },
    { city: 'Paramaribo', zone: 'America/Paramaribo' },
    { city: 'Asuncion', zone: 'America/Asuncion' },
    { city: 'Port of Spain', zone: 'America/Port_of_Spain' },
    { city: 'New York', zone: 'America/New_York' },
    { city: 'Detroit', zone: 'America/Detroit' },
    { city: 'Louisville', zone: 'America/Kentucky/Louisville' },
    { city: 'Monticello', zone: 'America/Kentucky/Monticello' },
    { city: 'Indianapolis', zone: 'America/Indiana/Indianapolis' },
    { city: 'Vincennes', zone: 'America/Indiana/Vincennes' },
    { city: 'Winamac', zone: 'America/Indiana/Winamac' },
    { city: 'Marengo', zone: 'America/Indiana/Marengo' },
    { city: 'Petersburg', zone: 'America/Indiana/Petersburg' },
    { city: 'Vevay', zone: 'America/Indiana/Vevay' },
    { city: 'Tell City', zone: 'America/Indiana/Tell_City' },
    { city: 'Knox', zone: 'America/Indiana/Knox' },
    { city: 'Chicago', zone: 'America/Chicago' },
    { city: 'Menominee', zone: 'America/Menominee' },
    { city: 'Denver', zone: 'America/Denver' },
    { city: 'Boise', zone: 'America/Boise' },
    { city: 'Phoenix', zone: 'America/Phoenix' },
    { city: 'Center', zone: 'America/North_Dakota/Center' },
    { city: 'New Salem', zone: 'America/North_Dakota/New_Salem' },
    { city: 'Beulah', zone: 'America/North_Dakota/Beulah' },
    { city: 'Los Angeles', zone: 'America/Los_Angeles' },
    { city: 'Anchorage', zone: 'America/Anchorage' },
    { city: 'Juneau', zone: 'America/Juneau' },
    { city: 'Sitka', zone: 'America/Sitka' },
    { city: 'Metlakatla', zone: 'America/Metlakatla' },
    { city: 'Yakutat', zone: 'America/Yakutat' },
    { city: 'Nome', zone: 'America/Nome' },
    { city: 'Adak', zone: 'America/Adak' },
    { city: 'Montevideo', zone: 'America/Montevideo' },
  ],
  Asia: [
    { city: 'Dubai', zone: 'Asia/Dubai' },
    { city: 'Kabul', zone: 'Asia/Kabul' },
    { city: 'Yerevan', zone: 'Asia/Yerevan' },
    { city: 'Baku', zone: 'Asia/Baku' },
    { city: 'Dhaka', zone: 'Asia/Dhaka' },
    { city: 'Brunei', zone: 'Asia/Brunei' },
    { city: 'Thimphu', zone: 'Asia/Thimphu' },
    { city: 'Shanghai', zone: 'Asia/Shanghai' },
    { city: 'Urumqi', zone: 'Asia/Urumqi' },
    { city: 'Nicosia', zone: 'Asia/Nicosia' },
    { city: 'Famagusta', zone: 'Asia/Famagusta' },
    { city: 'Tbilisi', zone: 'Asia/Tbilisi' },
    { city: 'Hong Kong', zone: 'Asia/Hong_Kong' },
    { city: 'Jakarta', zone: 'Asia/Jakarta' },
    { city: 'Pontianak', zone: 'Asia/Pontianak' },
    { city: 'Makassar', zone: 'Asia/Makassar' },
    { city: 'Jayapura', zone: 'Asia/Jayapura' },
    { city: 'Jerusalem', zone: 'Asia/Jerusalem' },
    { city: 'Kolkata', zone: 'Asia/Kolkata' },
    { city: 'Baghdad', zone: 'Asia/Baghdad' },
    { city: 'Tehran', zone: 'Asia/Tehran' },
    { city: 'Amman', zone: 'Asia/Amman' },
    { city: 'Tokyo', zone: 'Asia/Tokyo' },
    { city: 'Bishkek', zone: 'Asia/Bishkek' },
    { city: 'Pyongyang', zone: 'Asia/Pyongyang' },
    { city: 'Seoul', zone: 'Asia/Seoul' },
    { city: 'Almaty', zone: 'Asia/Almaty' },
    { city: 'Qyzylorda', zone: 'Asia/Qyzylorda' },
    { city: 'Qostanay', zone: 'Asia/Qostanay' },
    { city: 'Aqtobe', zone: 'Asia/Aqtobe' },
    { city: 'Aqtau', zone: 'Asia/Aqtau' },
    { city: 'Atyrau', zone: 'Asia/Atyrau' },
    { city: 'Oral', zone: 'Asia/Oral' },
    { city: 'Beirut', zone: 'Asia/Beirut' },
    { city: 'Colombo', zone: 'Asia/Colombo' },
    { city: 'Yangon', zone: 'Asia/Yangon' },
    { city: 'Ulaanbaatar', zone: 'Asia/Ulaanbaatar' },
    { city: 'Hovd', zone: 'Asia/Hovd' },
    { city: 'Choibalsan', zone: 'Asia/Choibalsan' },
    { city: 'Macau', zone: 'Asia/Macau' },
    { city: 'Kuala Lumpur', zone: 'Asia/Kuala_Lumpur' },
    { city: 'Kuching', zone: 'Asia/Kuching' },
    { city: 'Karachi', zone: 'Asia/Karachi' },
    { city: 'Gaza', zone: 'Asia/Gaza' },
    { city: 'Hebron', zone: 'Asia/Hebron' },
    { city: 'Kathmandu', zone: 'Asia/Kathmandu' },
    { city: 'Yekaterinburg', zone: 'Asia/Yekaterinburg' },
    { city: 'Qatar', zone: 'Asia/Qatar' },
    { city: 'Omsk', zone: 'Asia/Omsk' },
    { city: 'Novosibirsk', zone: 'Asia/Novosibirsk' },
    { city: 'Barnaul', zone: 'Asia/Barnaul' },
    { city: 'Tomsk', zone: 'Asia/Tomsk' },
    { city: 'Novokuznetsk', zone: 'Asia/Novokuznetsk' },
    { city: 'Krasnoyarsk', zone: 'Asia/Krasnoyarsk' },
    { city: 'Irkutsk', zone: 'Asia/Irkutsk' },
    { city: 'Chita', zone: 'Asia/Chita' },
    { city: 'Yakutsk', zone: 'Asia/Yakutsk' },
    { city: 'Khandyga', zone: 'Asia/Khandyga' },
    { city: 'Vladivostok', zone: 'Asia/Vladivostok' },
    { city: 'Ust-Nera', zone: 'Asia/Ust-Nera' },
    { city: 'Singapore', zone: 'Asia/Singapore' },
    { city: 'Magadan', zone: 'Asia/Magadan' },
    { city: 'Sakhalin', zone: 'Asia/Sakhalin' },
    { city: 'Srednekolymsk', zone: 'Asia/Srednekolymsk' },
    { city: 'Kamchatka', zone: 'Asia/Kamchatka' },
    { city: 'Anadyr', zone: 'Asia/Anadyr' },
    { city: 'Bangkok', zone: 'Asia/Bangkok' },
    { city: 'Dushanbe', zone: 'Asia/Dushanbe' },
    { city: 'Taipei', zone: 'Asia/Taipei' },
    { city: 'Dili', zone: 'Asia/Dili' },
    { city: 'Ashgabat', zone: 'Asia/Ashgabat' },
    { city: 'Damascus', zone: 'Asia/Damascus' },
    { city: 'Riyadh', zone: 'Asia/Riyadh' },
    { city: 'Samarkand', zone: 'Asia/Samarkand' },
    { city: 'Tashkent', zone: 'Asia/Tashkent' },
    { city: 'Ho Chi Minh', zone: 'Asia/Ho_Chi_Minh' },
  ],
  Europe: [
    { city: 'Andorra', zone: 'Europe/Andorra' },
    { city: 'Tirane', zone: 'Europe/Tirane' },
    { city: 'Vienna', zone: 'Europe/Vienna' },
    { city: 'Brussels', zone: 'Europe/Brussels' },
    { city: 'Sofia', zone: 'Europe/Sofia' },
    { city: 'Minsk', zone: 'Europe/Minsk' },
    { city: 'Zurich', zone: 'Europe/Zurich' },
    { city: 'Prague', zone: 'Europe/Prague' },
    { city: 'Berlin', zone: 'Europe/Berlin' },
    { city: 'Copenhagen', zone: 'Europe/Copenhagen' },
    { city: 'Tallinn', zone: 'Europe/Tallinn' },
    { city: 'Madrid', zone: 'Europe/Madrid' },
    { city: 'Helsinki', zone: 'Europe/Helsinki' },
    { city: 'Paris', zone: 'Europe/Paris' },
    { city: 'London', zone: 'Europe/London' },
    { city: 'Gibraltar', zone: 'Europe/Gibraltar' },
    { city: 'Athens', zone: 'Europe/Athens' },
    { city: 'Budapest', zone: 'Europe/Budapest' },
    { city: 'Dublin', zone: 'Europe/Dublin' },
    { city: 'Rome', zone: 'Europe/Rome' },
    { city: 'Vilnius', zone: 'Europe/Vilnius' },
    { city: 'Luxembourg', zone: 'Europe/Luxembourg' },
    { city: 'Riga', zone: 'Europe/Riga' },
    { city: 'Monaco', zone: 'Europe/Monaco' },
    { city: 'Chisinau', zone: 'Europe/Chisinau' },
    { city: 'Malta', zone: 'Europe/Malta' },
    { city: 'Amsterdam', zone: 'Europe/Amsterdam' },
    { city: 'Oslo', zone: 'Europe/Oslo' },
    { city: 'Warsaw', zone: 'Europe/Warsaw' },
    { city: 'Lisbon', zone: 'Europe/Lisbon' },
    { city: 'Bucharest', zone: 'Europe/Bucharest' },
    { city: 'Belgrade', zone: 'Europe/Belgrade' },
    { city: 'Kaliningrad', zone: 'Europe/Kaliningrad' },
    { city: 'Moscow', zone: 'Europe/Moscow' },
    { city: 'Simferopol', zone: 'Europe/Simferopol' },
    { city: 'Kirov', zone: 'Europe/Kirov' },
    { city: 'Astrakhan', zone: 'Europe/Astrakhan' },
    { city: 'Volgograd', zone: 'Europe/Volgograd' },
    { city: 'Saratov', zone: 'Europe/Saratov' },
    { city: 'Ulyanovsk', zone: 'Europe/Ulyanovsk' },
    { city: 'Samara', zone: 'Europe/Samara' },
    { city: 'Stockholm', zone: 'Europe/Stockholm' },
    { city: 'Istanbul', zone: 'Europe/Istanbul' },
    { city: 'Kiev', zone: 'Europe/Kiev' },
    { city: 'Uzhgorod', zone: 'Europe/Uzhgorod' },
    { city: 'Zaporozhye', zone: 'Europe/Zaporozhye' },
  ],
  Antarctica: [
    { city: 'Casey', zone: 'Antarctica/Casey' },
    { city: 'Davis', zone: 'Antarctica/Davis' },
    { city: 'DumontDUrville', zone: 'Antarctica/DumontDUrville' },
    { city: 'Mawson', zone: 'Antarctica/Mawson' },
    { city: 'Palmer', zone: 'Antarctica/Palmer' },
    { city: 'Rothera', zone: 'Antarctica/Rothera' },
    { city: 'Syowa', zone: 'Antarctica/Syowa' },
    { city: 'Troll', zone: 'Antarctica/Troll' },
    { city: 'Vostok', zone: 'Antarctica/Vostok' },
    { city: 'Macquarie', zone: 'Antarctica/Macquarie' },
  ],
  Pacific: [
    { city: 'Pago Pago', zone: 'Pacific/Pago_Pago' },
    { city: 'Rarotonga', zone: 'Pacific/Rarotonga' },
    { city: 'Easter', zone: 'Pacific/Easter' },
    { city: 'Galapagos', zone: 'Pacific/Galapagos' },
    { city: 'Fiji', zone: 'Pacific/Fiji' },
    { city: 'Chuuk', zone: 'Pacific/Chuuk' },
    { city: 'Pohnpei', zone: 'Pacific/Pohnpei' },
    { city: 'Kosrae', zone: 'Pacific/Kosrae' },
    { city: 'Guam', zone: 'Pacific/Guam' },
    { city: 'Majuro', zone: 'Pacific/Majuro' },
    { city: 'Kwajalein', zone: 'Pacific/Kwajalein' },
    { city: 'Tarawa', zone: 'Pacific/Tarawa' },
    { city: 'Enderbury', zone: 'Pacific/Enderbury' },
    { city: 'Kiritimati', zone: 'Pacific/Kiritimati' },
    { city: 'Noumea', zone: 'Pacific/Noumea' },
    { city: 'Norfolk', zone: 'Pacific/Norfolk' },
    { city: 'Nauru', zone: 'Pacific/Nauru' },
    { city: 'Niue', zone: 'Pacific/Niue' },
    { city: 'Auckland', zone: 'Pacific/Auckland' },
    { city: 'Chatham', zone: 'Pacific/Chatham' },
    { city: 'Tahiti', zone: 'Pacific/Tahiti' },
    { city: 'Marquesas', zone: 'Pacific/Marquesas' },
    { city: 'Gambier', zone: 'Pacific/Gambier' },
    { city: 'Port Moresby', zone: 'Pacific/Port_Moresby' },
    { city: 'Bougainville', zone: 'Pacific/Bougainville' },
    { city: 'Pitcairn', zone: 'Pacific/Pitcairn' },
    { city: 'Palau', zone: 'Pacific/Palau' },
    { city: 'Guadalcanal', zone: 'Pacific/Guadalcanal' },
    { city: 'Fakaofo', zone: 'Pacific/Fakaofo' },
    { city: 'Tongatapu', zone: 'Pacific/Tongatapu' },
    { city: 'Funafuti', zone: 'Pacific/Funafuti' },
    { city: 'Wake', zone: 'Pacific/Wake' },
    { city: 'Honolulu', zone: 'Pacific/Honolulu' },
    { city: 'Efate', zone: 'Pacific/Efate' },
    { city: 'Wallis', zone: 'Pacific/Wallis' },
    { city: 'Apia', zone: 'Pacific/Apia' },
  ],
  Australia: [
    { city: 'Lord Howe', zone: 'Australia/Lord_Howe' },
    { city: 'Hobart', zone: 'Australia/Hobart' },
    { city: 'Currie', zone: 'Australia/Currie' },
    { city: 'Melbourne', zone: 'Australia/Melbourne' },
    { city: 'Sydney', zone: 'Australia/Sydney' },
    { city: 'Broken Hill', zone: 'Australia/Broken_Hill' },
    { city: 'Brisbane', zone: 'Australia/Brisbane' },
    { city: 'Lindeman', zone: 'Australia/Lindeman' },
    { city: 'Adelaide', zone: 'Australia/Adelaide' },
    { city: 'Darwin', zone: 'Australia/Darwin' },
    { city: 'Perth', zone: 'Australia/Perth' },
    { city: 'Eucla', zone: 'Australia/Eucla' },
  ],
  Africa: [
    { city: 'Abidjan', zone: 'Africa/Abidjan' },
    { city: 'Algiers', zone: 'Africa/Algiers' },
    { city: 'Cairo', zone: 'Africa/Cairo' },
    { city: 'El Aaiun', zone: 'Africa/El_Aaiun' },
    { city: 'Ceuta', zone: 'Africa/Ceuta' },
    { city: 'Accra', zone: 'Africa/Accra' },
    { city: 'Bissau', zone: 'Africa/Bissau' },
    { city: 'Nairobi', zone: 'Africa/Nairobi' },
    { city: 'Monrovia', zone: 'Africa/Monrovia' },
    { city: 'Tripoli', zone: 'Africa/Tripoli' },
    { city: 'Casablanca', zone: 'Africa/Casablanca' },
    { city: 'Maputo', zone: 'Africa/Maputo' },
    { city: 'Windhoek', zone: 'Africa/Windhoek' },
    { city: 'Lagos', zone: 'Africa/Lagos' },
    { city: 'Khartoum', zone: 'Africa/Khartoum' },
    { city: 'Juba', zone: 'Africa/Juba' },
    { city: 'Sao Tome', zone: 'Africa/Sao_Tome' },
    { city: 'Ndjamena', zone: 'Africa/Ndjamena' },
    { city: 'Tunis', zone: 'Africa/Tunis' },
    { city: 'Johannesburg', zone: 'Africa/Johannesburg' },
  ],
  Atlantic: [
    { city: 'Azores', zone: 'Atlantic/Azores' },
    { city: 'Bermuda', zone: 'Atlantic/Bermuda' },
    { city: 'Madeira', zone: 'Atlantic/Madeira' },
    { city: 'Cape Verde', zone: 'Atlantic/Cape_Verde' },
    { city: 'Canary', zone: 'Atlantic/Canary' },
    { city: 'Stanley', zone: 'Atlantic/Stanley' },
    { city: 'Faroe', zone: 'Atlantic/Faroe' },
    { city: 'South Georgia', zone: 'Atlantic/South_Georgia' },
    { city: 'Reykjavik', zone: 'Atlantic/Reykjavik' },
  ],
  Indian: [
    { city: 'Cocos', zone: 'Indian/Cocos' },
    { city: 'Christmas', zone: 'Indian/Christmas' },
    { city: 'Chagos', zone: 'Indian/Chagos' },
    { city: 'Mauritius', zone: 'Indian/Mauritius' },
    { city: 'Maldives', zone: 'Indian/Maldives' },
    { city: 'Mahe', zone: 'Indian/Mahe' },
    { city: 'Reunion', zone: 'Indian/Reunion' },
    { city: 'Kerguelen', zone: 'Indian/Kerguelen' },
  ],
} as const;
